# 
FROM python:3.11

#
RUN apt update && apt install -y s3fs
# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./ /code

# 
CMD ["pytest", "tests/"]
